name: Create release with input

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag: (vx.x.x)'
        required: true
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: "Create release with input"
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: CSchoel/release-notes-from-changelog@v1.3.0
        with:
          version: ${{ inputs.tag }}
      - name: Create Release using GitHub CLI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >
          gh release create
          -d
          -F RELEASE.md
          -t "Version $RELEASE_VERSION"
          ${GITHUB_REF#refs/*/}
