name: Create release with zip external

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag: (vX.X.X)'
        required: true
        type: string
      title:
        description: 'Release title:'
        required: false
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: "Create release with zip external"
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: CSchoel/release-notes-from-changelog@v1.3.0
        with:
          version: ${{ inputs.tag }}
      - name: "Create Release using GitHub CLI"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >
          gh release create
          -F RELEASE.md
          -t "${{ inputs.tag }} - ${{ inputs.title }}"
          ${{ inputs.tag }}
      - name: "Get binaries"
        id: curl
        uses: dedene/curl@v1
        with:
          url: https://raw.githubusercontent.com/regorxxx/foobar2000-assets/main/Spider%20Monkey%20Panel/foo_spider_monkey_panel-v1.6.1-mod.fb2k-component
          args: -v
      - uses: AButler/upload-release-assets@v3.0
        with:
          files: "${{ steps.curl.curl_output }}"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{ inputs.tag }}
