name: Create release + SMP + package

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag: (X.X.X)'
        required: true
        type: string
      title:
        description: 'Release title:'
        required: false
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
    name: "Create release"
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ inputs.tag }}
      - uses: CSchoel/release-notes-from-changelog@v1.3.0
        with:
          version: ${{ inputs.tag }}
      - name: "Create Release using GitHub CLI"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >
          gh release create
          -F RELEASE.md
          -t "${{ inputs.tag }} - ${{ inputs.title }}"
          ${{ inputs.tag }}

  mod:
    name: "Attatch SMP mod"
    runs-on: ubuntu-latest
    
    steps:
      - name: "Get binaries"
        run: |
          curl -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
          -H 'Accept: application/vnd.github.v4.raw' \
          -O \
          -L https://api.github.com/repos/regorxxx/foobar2000-assets/contents/Spider%20Monkey%20Panel/foo_spider_monkey_panel-v1.6.1-mod.fb2k-component    
      - uses: AButler/upload-release-assets@v3.0
        with:
          files: "foo_spider_monkey_panel-v1.6.1-mod.fb2k-component"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{ inputs.tag }}

  package:
    name: "Attatch Package"
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4.1.1
      - name: "Create package"
        run: ./_createPackage.bat 2
      - uses: AButler/upload-release-assets@v3.0
        with:
          files: "packages/*.zip"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{ inputs.tag }}
